export const SET_ORDER = 'SET_ORDER';
export const SET_SEARCH_NAME = 'SET_SEARCH_NAME';
export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT';
export const SET_CURRENT_CONTACT_ID = 'SET_CURRENT_CONTACT_ID';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';

export const LOAD_CONTACTS_START = 'LOAD_CONTACTS_START';
export const LOAD_CONTACTS_SUCCESS = 'LOAD_CONTACTS_SUCCESS';
export const LOAD_CONTACTS_ERROR = 'LOAD_CONTACTS_ERROR';

export const CREATE_CONTACT_START = 'CREATE_CONTACT_START';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR';

export const DELETE_CONTACT_START = 'DELETE_CONTACT_START';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';
